name: Build OpenWrt

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile OpenWrt Firmware

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
        gettext git libncurses-dev libssl-dev rsync unzip zlib1g-dev file wget python3 python3-pip


    - name: Clone OpenWrt source
      run: |
        git clone https://github.com/openwrt/openwrt.git openwrt
        cd openwrt
        git checkout v24.10

    - name: Load custom feeds config
      run: |
        cp -f ./config/feeds.conf.default ./openwrt/feeds.conf.default

    - name: Update and install feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load custom config
      run: |
        cp -f ./config/.config ./openwrt/.config

    - name: Build firmware
      run: |
        cd openwrt
        make defconfig
        make -j$(nproc)
      
