name: Build OpenWrt

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "Select the source branch"
        required: false
        default: "immortalwrt-master"
        type: choice
        options:
          - openwrt-main
          - lede-master
          - immortalwrt-master
      openwrt_board:
        description: "Select device board"
        required: false
        default: "all"
        type: choice
        options:
          - all
          - s905x
          - s912
          - rock5b
          - orangepi-5-plus
      openwrt_kernel:
        description: "Select kernel version"
        required: false
        default: "6.1.y_6.12.y"
        type: choice
        options:
          - 5.4.y
          - 5.10.y
          - 5.15.y
          - 6.1.y
          - 6.6.y
          - 6.12.y
          - 5.4.y_5.10.y
          - 5.15.y_6.1.y
          - 6.1.y_6.12.y
      auto_kernel:
        description: "Auto use the latest kernel"
        required: false
        default: true
        type: boolean

env:
  TZ: Asia/Jakarta

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout this workflow repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex g++ gawk gcc-multilib \
            help2man texinfo libtool libncurses5-dev libncursesw5-dev zlib1g-dev \
            file wget unzip python3 python3-distutils rsync subversion asciidoc \
            libssl-dev libelf-dev ecj fastjar java-propose-classpath \
            libglib2.0-dev xmlto ccache ninja-build

      - name: Set OpenWrt repo URL
        id: repo
        run: |
          case "${{ inputs.source_branch }}" in
            lede-master)
              echo "url=https://github.com/coolsnowwolf/lede.git" >> "$GITHUB_OUTPUT"
              ;;
            immortalwrt-master)
              echo "url=https://github.com/immortalwrt/immortalwrt.git" >> "$GITHUB_OUTPUT"
              ;;
            *)
              echo "url=https://github.com/openwrt/openwrt.git" >> "$GITHUB_OUTPUT"
              ;;
          esac

      - name: Clone OpenWrt
        run: git clone --depth 1 --branch ${{ inputs.source_branch }} ${{ steps.repo.outputs.url }} openwrt

      - name: Update feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure default
        run: |
          cd openwrt
          make defconfig

      - name: Build OpenWrt firmware
        run: |
          cd openwrt
          make -j$(nproc) V=s
