on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "Source branch"
        required: false
        default: "openwrt-main"
      openwrt_board:
        description: "Device board"
        required: false
        default: "all"
      openwrt_kernel:
        description: "Kernel version"
        required: false
        default: "6.1.y_6.12.y"
      build_action:
        description: "Build mode"
        required: false
        default: "all"
      build_target:
        description: "Build target"
        required: false
        default: "armvirt"
      build_version:
        description: "Firmware version"
        required: false
        default: "auto"
      luci_theme:
        description: "LuCI theme"
        required: false
        default: "auto"
      upload_firmware:
        description: "Upload firmware?"
        required: false
        default: "true"
      upload_release:
        description: "Upload release artifact?"
        required: false
        default: "true"
      server_chan_sckey:
        description: "ServerChan SCKEY"
        required: false
        default: ""
      
