name: Build OpenWrt

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "Pilih branch OpenWrt yang ingin di-build"
        required: true
        default: openwrt-24.10
        type: choice
        options:
          - openwrt-24.10
          - openwrt-23.05
          - openwrt-22.03
          - main
          - lede-master
          - immortalwrt-master
      openwrt_board:
        description: "Pilih device board (misal: s905x, s912, rock5b, dll)"
        required: false
        default: all
        type: choice
        options:
          - all
          - s905x
          - s912
          - rock5b
          - orangepi-5-plus
      openwrt_kernel:
        description: "Pilih versi kernel Linux"
        required: false
        default: 6.1.y_6.12.y
        type: choice
        options:
          - 5.4.y
          - 5.10.y
          - 5.15.y
          - 6.1.y
          - 6.6.y
          - 6.12.y
          - 5.4.y_5.10.y
          - 5.15.y_6.1.y
          - 6.1.y_6.12.y
      auto_kernel:
        description: "Otomatis pakai kernel terbaru"
        required: false
        default: true
        type: boolean

env:
  TZ: Asia/Jakarta

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout OpenWrt Source
        run: |
          # Sesuaikan repo sesuai branch
          if [[ "${{ inputs.source_branch }}" == "immortalwrt-master" ]]; then
            git clone --depth 1 --branch master https://github.com/immortalwrt/immortalwrt.git openwrt
          elif [[ "${{ inputs.source_branch }}" == "lede-master" ]]; then
            git clone --depth 1 --branch master https://github.com/coolsnowwolf/lede.git openwrt
          else
            git clone --depth 1 --branch ${{ inputs.source_branch }} https://github.com/openwrt/openwrt.git openwrt
          fi

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang clang++ flex g++ gawk gcc-multilib \
            help2man texinfo libtool libncurses5-dev libncursesw5-dev zlib1g-dev \
            file wget unzip python3 python3-distutils rsync subversion asciidoc \
            libssl-dev libelf-dev ecj fastjar java-propose-classpath \
            libglib2.0-dev xmlto ccache ninja-build

      - name: Update & Install Feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Prepare Default Config
        run: |
          cd openwrt
          make defconfig

      - name: Build OpenWrt Firmware
        run: |
          cd openwrt
          make -j$(nproc) V=s
