name: Build OpenWrt

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "Select source branch"
        required: false
        default: "openwrt-main"
        type: choice
        options:
          - openwrt-main
          - lede-master
          - immortalwrt-master
      openwrt_board:
        description: "Target device board"
        required: false
        default: "s905x"
        type: string
      openwrt_kernel:
        description: "Kernel version"
        required: false
        default: "6.1.y"
        type: string

env:
  TZ: Asia/Jakarta
  CONFIG_FILE: config/${{ inputs.source_branch }}/config
  FEEDS_CONF: config/${{ inputs.source_branch }}/feeds.conf.default
  DIY_P1_SH: config/${{ inputs.source_branch }}/diy-part1.sh
  DIY_P2_SH: config/${{ inputs.source_branch }}/diy-part2.sh

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Init environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential flex bison clang gawk gcc-multilib g++-multilib \
              gettext libncurses5-dev libssl-dev python3 python3-pip unzip wget subversion rsync \
              libz-dev file

      - name: Clone OpenWrt source
        run: |
          case "${{ inputs.source_branch }}" in
            openwrt-main)
              git clone --depth 1 --branch main https://github.com/openwrt/openwrt.git openwrt
              ;;
            lede-master)
              git clone --depth 1 --branch master https://github.com/coolsnowwolf/lede.git openwrt
              ;;
            immortalwrt-master)
              git clone --depth 1 --branch master https://github.com/immortalwrt/immortalwrt.git openwrt
              ;;
            *)
              echo "Invalid branch selected"
              exit 1
              ;;
          esac

      - name: Apply feeds and custom config
        run: |
          cp -f ${FEEDS_CONF} openwrt/feeds.conf.default || true
          chmod +x ${DIY_P1_SH} ${DIY_P2_SH} || true
          cd openwrt
          [ -f ${GITHUB_WORKSPACE}/${DIY_P1_SH} ] && ${GITHUB_WORKSPACE}/${DIY_P1_SH}
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          [ -f ${GITHUB_WORKSPACE}/${CONFIG_FILE} ] && cp ${GITHUB_WORKSPACE}/${CONFIG_FILE} .config
          [ -f ${GITHUB_WORKSPACE}/${DIY_P2_SH} ] && ${GITHUB_WORKSPACE}/${DIY_P2_SH}

      - name: Build OpenWrt
        run: |
          cd openwrt
          make defconfig
          make download -j$(nproc)
          make -j$(nproc) || make -j1 V=s

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-firmware
          path: openwrt/bin/targets
          
